/* String t is generated by random shuffling string s and then add one more letter at a random position.
‌
 Return the letter that was added to */


public class Problem4 {
    public static char missingLetter(String s, String t) {
        int[] count = new int[26];

        for (char ch : t.toCharArray()) {
            count[ch - 'a']++;
        }
        for (char ch : s.toCharArray()) {
            count[ch - 'a']--;
        }

        for (int i = 0; i < 26; i++) {
            if (count[i] == 1) {
                return (char) ('a' + i);
            }
        }

        return '0'; 
    }

    public static void main(String[] args) {
        String s = "abcd";
        String t = "abcde";
        System.out.println("Missing letter was: " + missingLetter(s, t));
    }
}


	  